### ISSUE TITLE
Dependency fetching http 404 warning/errors during install of build-essential

### ISSUE THREAD

**Issue by mystique100** [seekthex/CHC_Wallets#2]
The following line in function build_chc_wallet() resulted in dependency fetching error/warnings:

    package sudo apt-get install build-essential -y

Resulting in the following dependency fetching warnings/error:

> Err:23 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libquadmath0 amd64 5.4.0-6ubuntu1~16.04.4
>   404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> Err:24 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libgcc-5-dev amd64 5.4.0-6ubuntu1~16.04.4
>   404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> Err:25 http://security.ubuntu.com/ubuntu xenial-security/main amd64 gcc-5 amd64 5.4.0-6ubuntu1~16.04.4
>   404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> Err:27 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libstdc++-5-dev amd64 5.4.0-6ubuntu1~16.04.4
>   404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> Err:28 http://security.ubuntu.com/ubuntu xenial-security/main amd64 g++-5 amd64 5.4.0-6ubuntu1~16.04.4
>   404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> Get:42 http://mirrors.linode.com/ubuntu xenial/main amd64 rename all 0.20-4 [12.0 kB]
> Err:31 http://mirrors.linode.com/ubuntu xenial-updates/main i386 libdpkg-perl all 1.18.4ubuntu1.1
>   404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> Err:33 http://mirrors.linode.com/ubuntu xenial-updates/main i386 dpkg-dev all 1.18.4ubuntu1.1
>   404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> Fetched 9,533 kB in 0s (34.6 MB/s)
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/b/binutils/binutils_2.26.1-1ubuntu1~16.04.3_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://mirrors.linode.com/ubuntu/pool/main/g/glibc/libc-dev-bin_2.23-0ubuntu5_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.4.0-64.85_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://mirrors.linode.com/ubuntu/pool/main/g/glibc/libc6-dev_2.23-0ubuntu5_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/cpp-5_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libcc1-0_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libgomp1_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libitm1_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libatomic1_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libasan2_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/liblsan0_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libtsan0_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libubsan0_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libcilkrts5_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libmpx0_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libquadmath0_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libgcc-5-dev_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/gcc-5_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++-5-dev_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/g++-5_5.4.0-6ubuntu1~16.04.4_amd64.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://mirrors.linode.com/ubuntu/pool/main/d/dpkg/libdpkg-perl_1.18.4ubuntu1.1_all.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Failed to fetch http://mirrors.linode.com/ubuntu/pool/main/d/dpkg/dpkg-dev_1.18.4ubuntu1.1_all.deb  404  Not Found [IP: 2a01:7e00:1::b24f:af37 80]
> 
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

A suggestion would be to add the following as the first command in the function build_chc_wallet():

    sudo apt-get update

Adding the above line resolved most of the dependency fetching issues

**Comment by seekthex** [comment]
Thank you I have added the suggested line
